# Generated by Django 5.1.4 on 2025-02-11 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_id_alter_user_phone_number'),
        ('api', '0005_user_id_alter_user_phone_number'),
    ]

    operations = [
    ]
