name: Backend Actions
on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
      - dev
defaults:
  run:
    working-directory: backend
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          src: "./backend"
