name: Frontend Actions
on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
      - dev

defaults:
  run:
    working-directory: frontend

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install 
          npm run lint
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: |
  #         npm install
  #         npm run build
